pipeline
{
    agent any
    tools 
    {
        maven 'my-maven'
    }
    environment {
        Name = "Bharath"
    }
    parameters {
  string defaultValue: 'Kumar N R', name: 'lastname'
}



    stages
    {
        stage('build') 
        {
             steps 
             {
                sh 'mvn clean package'
                echo "hello ${name} ${params.lastname}"
             }
        post 
        {
            success 
            {
                archiveArtifacts artifacts: '**/target/*.jar'
            }
        }
        }

   }
}